// <auto-generated />
namespace THOT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nine));
        
        string IMigrationMetadata.Id
        {
            get { return "201610242311217_Nine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
